// Resolves a figure's authored PDF path (as written in `<Figure src="figures/pdf/...pdf">`)
// to its generated SVG rendering (URL + intrinsic size), produced by
// `npm run convert:figures` (scripts/convert-figures.mjs) and committed alongside the source
// PDF under the same name. The PDF stays the source of truth; the SVG is what actually
// renders, so the site doesn't depend on poppler being available at CI build time.
import { readFileSync } from 'node:fs';
import path from 'node:path';

const FIGURES_ROOT = path.resolve(process.cwd(), 'src/contents/full_paper');

const svgUrls = import.meta.glob('../contents/full_paper/figures/**/*.svg', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>;

const dimensionCache = new Map<string, { width: number; height: number }>();

// pdftocairo writes the SVG's width/height in pt, matching the PDF page size — which for
// these standalone-cropped figure PDFs is the figure's own natural size, not an
// author-chosen include width. Reading it back lets subfigures (e.g. fig:stats) be laid out
// at a shared scale instead of independently stretched to equal container widths, which is
// what made mismatched subfigures look broken (different heights, one dwarfing the other).
function readDimensions(svgRelPath: string): { width: number; height: number } {
  const cached = dimensionCache.get(svgRelPath);
  if (cached) return cached;

  const filePath = path.join(FIGURES_ROOT, svgRelPath);
  const contents = readFileSync(filePath, 'utf-8');
  const match = contents.match(/width="([\d.]+)pt"\s+height="([\d.]+)pt"/);
  if (!match) {
    throw new Error(`Could not read pt dimensions from ${filePath} — was it generated by pdftocairo -svg?`);
  }
  const dims = { width: Number(match[1]), height: Number(match[2]) };
  dimensionCache.set(svgRelPath, dims);
  return dims;
}

export interface FigureAsset {
  url: string;
  width: number;
  height: number;
}

export function getFigureAsset(pdfPath: string): FigureAsset {
  const rel = pdfPath.trim().replace(/\.pdf$/, '.svg');
  const key = `../contents/full_paper/${rel}`;
  const url = svgUrls[key];
  if (!url) {
    throw new Error(
      `No generated SVG found for figure "${pdfPath}" (expected ${key}). Run \`npm run convert:figures\` after adding the PDF.`,
    );
  }
  return { url, ...readDimensions(rel) };
}
