// Build-time loader for the distilled system/benchmark records.
//
// Mirrors paper-tables.ts: a synchronous, memoized filesystem read rather than a content
// collection, because these are two files consumed by exactly one page each.
//
// Unlike the paper's transcribed tables, these files are *generated* — by
// `npm run sync:paper-data` (scripts/sync-paper-data.mjs) from the evidence records in the
// gitignored .local/ folder. They are committed so CI, which never sees .local, can build.
// Edit the records in .local and re-run the sync; never hand-edit the generated JSON.
import { readFileSync } from 'node:fs';
import path from 'node:path';

const DATA_DIR = path.resolve(process.cwd(), 'src/contents/data');

export interface SystemRecord {
  citekey: string;
  name: string;
  dataSetting: string;
  orchestration: string;
  capabilities: {
    interpretation: string[];
    retrieval: string[];
    analysis: string[];
    output: string[];
    governance: string[];
  };
  inputModes: string[];
  datasets: string[];
}

export interface BenchmarkRecord {
  citekey: string;
  name: string;
  corpus: {
    numTables: string;
    format: string;
    provenance: string;
    additionalData: string;
    assembly: string;
  };
  setting: {
    numInstances: string;
    dataSetting: string;
    outputModalities: string[];
  };
  interaction: {
    inputProtocol: string;
  };
  validation: {
    functions: string[];
  };
  insightTypes: { type: string; requiresArtifact: boolean }[];
  /** False when the types are analysis-derived rather than transcribed from Table 5. */
  insightTypesAuthoritative: boolean;
  /** True for the subset the paper's space-limited Table 5 shows. */
  inOverviewTable: boolean;
}

const cache = new Map<string, unknown>();

function load<T>(file: string): T {
  const cached = cache.get(file);
  if (cached) return cached as T;

  const filePath = path.join(DATA_DIR, file);
  let raw: string;
  try {
    raw = readFileSync(filePath, 'utf-8');
  } catch (error) {
    throw new Error(
      `Could not read ${filePath}. It is generated by \`npm run sync:paper-data\` from the ` +
        'evidence records in .local/paper/data/ and is meant to be committed — see CLAUDE.md.',
      { cause: error },
    );
  }

  const parsed = JSON.parse(raw) as T;
  cache.set(file, parsed);
  return parsed;
}

export function getSystemRecords(): SystemRecord[] {
  return load<SystemRecord[]>('systems.json');
}

export function getBenchmarkRecords(): BenchmarkRecord[] {
  return load<BenchmarkRecord[]>('benchmarks.json');
}
